// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "heroTitle": "Hello world.",
  "helloMessage": "Hello {name}!",
  "global": {
    "reset": "Reset"
  },
  "pluralizationExample": "{count, plural,\n  =0 {The count has not been changed.}\n  =-1 {The count has been changed to -1.}\n  one {The count has been changed to 1.}\n  other {The count has been changed to #.}\n}",
  "linkExample": "This example includes a <link>link</link>!"
};
export default messages;